.TH "Constantes" 3 "Wed Dec 18 2013" "Version 1.0" "LDH_Hospital_Desmoj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constantes \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBtiempoSimulacion\fP = 1000"
.br
.ti -1c
.RI "static int \fBcantidadCamas\fP [] = {10, 5}"
.br
.ti -1c
.RI "static double \fBporLlegadas\fP [] = {6, 3}"
.br
.ti -1c
.RI "static double \fBtiempoEnSistema\fP [] = {60, 60}"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Constantes\&.cantidadCamas[] = {10, 5}\fC [static]\fP"

.SS "double Constantes\&.porLlegadas[] = {6, 3}\fC [static]\fP"

.SS "double Constantes\&.tiempoEnSistema[] = {60, 60}\fC [static]\fP"

.SS "int Constantes\&.tiempoSimulacion = 1000\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LDH_Hospital_Desmoj from the source code\&.
