.TH "src/Paciente.java" 3 "Wed Dec 18 2013" "Version 1.0" "LDH_Hospital_Desmoj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Paciente.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPaciente\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LDH_Hospital_Desmoj from the source code\&.
