.TH "Paciente" 3 "Wed Dec 18 2013" "Version 1.0" "LDH_Hospital_Desmoj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Paciente \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SimProcess\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaciente\fP (Model owner, String name, int \fBid\fP, boolean showInTrace)"
.br
.ti -1c
.RI "void \fBlifeCycle\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBModeloHospital\fP \fBmyModel\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Paciente\&.Paciente (Modelowner, Stringname, intid, booleanshowInTrace)"

.SH "Member Function Documentation"
.PP 
.SS "void Paciente\&.lifeCycle ()"

.SH "Member Data Documentation"
.PP 
.SS "int Paciente\&.id\fC [private]\fP"

.SS "\fBModeloHospital\fP Paciente\&.myModel\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LDH_Hospital_Desmoj from the source code\&.
