.TH "Pacientes" 3 "Wed Dec 18 2013" "Version 1.0" "LDH_Hospital_Desmoj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pacientes \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ExternalEvent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBeventRoutine\fP ()"
.br
.ti -1c
.RI "\fBPacientes\fP (Model owner, boolean showInTrace)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBcuantos\fP"
.br
.ti -1c
.RI "int \fBcuantosEmergencia\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Pacientes\&.Pacientes (Modelowner, booleanshowInTrace)"

.SH "Member Function Documentation"
.PP 
.SS "void Pacientes\&.eventRoutine ()"

.SH "Member Data Documentation"
.PP 
.SS "int Pacientes\&.cuantos\fC [private]\fP"

.SS "int Pacientes\&.cuantosEmergencia\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LDH_Hospital_Desmoj from the source code\&.
