.TH "Prueba_Hospital" 3 "Wed Dec 18 2013" "Version 1.0" "LDH_Hospital_Desmoj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prueba_Hospital \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP (\fBModeloHospital\fP hospital)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Prueba_Hospital\&.test (\fBModeloHospital\fPhospital)"


.SH "Author"
.PP 
Generated automatically by Doxygen for LDH_Hospital_Desmoj from the source code\&.
